apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: authentik
      version: "2024.2.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  releaseName: authentik
  targetNamespace: identity
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: authentik-db
  valuesFrom:
    - kind: Secret
      name: authentik.identity-db.credentials.postgresql.acid.zalan.do
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secret-key
      valuesKey: secretkey
      targetPath: authentik.secret_key

  values:
    global:
      envFrom:
        - secretRef:
            name: authentik-bootstrap
      envValueFrom:
        AUTHENTIK_BOOTSTRAP_PASSWORD:
          secretKeyRef:
            key: password
            name: authentik-bootstrap
        AUTHENTIK_BOOTSTRAP_TOKEN:
          secretKeyRef:
            key: token
            name: authentik-bootstrap
        AUTHENTIK_BOOTSTRAP_EMAIL:
          secretKeyRef:
            key: email
            name: authentik-bootstrap
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule

    authentik:
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      email:
        host: ${smtp_server}
        port: ${smtp_port}
        username: ${smtp_user}
        password: ${smtp_password}
        use_tls: ${smtp_tls}
        from: ${from_email}
      error_reporting:
        enabled: false
      postgresql:
        host: identity-db
    server:
      ingress:
        enabled: true
        annotations:
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/ssl-redirect: "443"
        tls:
          - hosts:
              - identity.ref.logsr.life
        hosts:
          - identity.ref.logsr.life
        ingressClassName: alb-partition
      replicas: 2
      pdb:
        enabled: true
        maxUnavailable: 1
    worker:
      replicas: 2
      pdb:
        enabled: true
        minAvailable: 1
    redis:
      enabled: true
