apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-repos
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/metrics-server/
