apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: keda
      version: "2.13.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-repos
      interval: 5m
  releaseName: keda-operator
  targetNamespace: keda-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: metrics-server
    - name: cert-manager
  values:
    podIdentity:
      aws:
        irsa:
          roleArn: ${iam_role_arn}
          enabled: true
    logging:
      operator:
        format: json
      webhooks:
        format: json
    certificates:
      certManager:
        enabled: true
    operator:
      replicaCount: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - keda-operator
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
    metricServer:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - keda-operator-metrics-apiserver
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux

    webhooks:
      replicaCount: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - keda-admission-webhooks
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux

      topologySpreadConstraints:
        - maxSkew: 2
          minDomains: 2
          whenUnsatisfiable: DoNotSchedule
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app: keda-admission-webhooks
          matchLabelKeys:
            - pod-template-hash
      priorityClassName: "system-cluster-critical"
