apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: karpenter
      version: "0.35.0"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-repos
      interval: 5m
  releaseName: karpenter
  targetNamespace: karpenter
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    replicas: 2
    settings:
      clusterName: ${cluster_name}
      clusterEndpoint: ${cluster_endpoint}
      interruptionQueueName: ${queue_name}
      aws:
        enablePodENU: true
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${iam_role_arn}
    controller:
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 1
          memory: 256Mi
    podDisruptionBudget:
      enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - karpenter
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - karpenter
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: karpenter
            app.kubernetes.io/instance: karpenter
        matchLabelKeys:
          - pod-template-hash
    priorityClassName: "system-cluster-critical"
