apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: redis-operator
      version: "0.18.0"
      sourceRef:
        kind: HelmRepository
        name: ot-operators
        namespace: flux-repos
      interval: 5m
  releaseName: redis-operator
  targetNamespace: redis-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
