apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zalando-ui
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: "postgres-operator-ui"
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: zalando-pg-ui
        namespace: flux-repos
      interval: 5m
  dependsOn:
    - name: zalando
  releaseName: zalando-ui
  targetNamespace: postgres-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - zalando-ui
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - postgres-operator-ui
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: postgres-operator-ui
            app.kubernetes.io/instance: zalando-ui
        matchLabelKeys:
          - pod-template-hash
