apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zalando
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: "postgres-operator"
      version: "1.12.2"
      sourceRef:
        kind: HelmRepository
        name: zalando-pg
        namespace: flux-repos
      interval: 5m
  releaseName: zalando
  targetNamespace: postgres-operator
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment

  values:
    enableJsonLogging: true
    configAwsOrGcp:
      aws_region: ${region}
    replicas: 2
    configKubernetes:
      enable_finalizers: true
      enable_pod_antiaffinity: true
      persistent_volume_claim_retention_policy:
        when_deleted: "delete"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - zalando
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - postgres-operator
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: postgres-operator
            app.kubernetes.io/instance: zalando
        matchLabelKeys:
          - pod-template-hash
